#!/usr/bin/python

# Ubuntu Tweak - PyGTK based desktop configure tool
#
# Copyright (C) 2007-2008 TualatriX <tualatrix@gmail.com>
#
# Ubuntu Tweak is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Ubuntu Tweak is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ubuntu Tweak; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA

import dbus
import dbus.service
import dbus.mainloop.glib
import gobject

class DemoException(dbus.DBusException):
    _dbus_error_name = 'com.ubuntu_tweak.Mechanism.DemoException'

class Tweak(dbus.service.Object):
    INTERFACE = "com.ubuntu_tweak.Mechanism"
    liststate = None

    @dbus.service.method(INTERFACE,
                         in_signature='sssb', out_signature='s')
    def SetSourcesList(self, url, comment, comps, enabled):
        import apt_pkg
        from aptsources.sourceslist import SourceEntry, SourcesList
        apt_pkg.init()
        list = SourcesList()
        self.liststate = "expire"
        if enabled:
            list.add('deb', url, 'hardy', [comps], comment)
        #    list.add('deb-src', url, 'hardy', [comps], comment)
            list.save()
            return 'enabled'
        else:
            for entry in list:
                if url in entry.str():
                    entry.disabled = True

            list.save()
            return 'disabled'

    @dbus.service.method(INTERFACE,
                         in_signature='', out_signature='s')
    def GetListState(self):
        if self.liststate:
            return self.liststate
        else:
            return "normal"
            
    @dbus.service.method(INTERFACE,
                         in_signature='s', out_signature='')
    def SetListState(self, state):
        self.liststate = state

    @dbus.service.method(INTERFACE,
                         in_signature='', out_signature='')
    def Exit(self):
        mainloop.quit()

if __name__ == '__main__':
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    system_bus = dbus.SystemBus()
    name = dbus.service.BusName("com.ubuntu_tweak.Mechanism", system_bus)
    object = Tweak(system_bus, '/Tweak')

    mainloop = gobject.MainLoop()
    mainloop.run()
