#!/bin/bash

MPLAYER_DIR=`echo ~/.mplayer`

if [ ! -d $MPLAYER_DIR ]; then
	mkdir ~/.mplayer
fi

#MPLAYER Settings
MPLAYER_GUI_CONF=`echo ~/.mplayer/gui.conf`
MPLAYER_CONFIG=`echo ~/.mplayer/config`

VO_DRIVER=`grep "vo_driver" $MPLAYER_GUI_CONF 2>/dev/null`
VO_DRIVER_VALUE=`grep "vo_driver" $MPLAYER_GUI_CONF 2>/dev/null | awk -F"\"" '{print $2}' `
ZOOM=`grep "zoom" $MPLAYER_CONFIG 2>/dev/null`
ZOOM_VALUE=`grep "zoom" $MPLAYER_CONFIG 2>/dev/null | sed -n '/[ytru]/p'`
SUB_FUZZINESS=`grep  "sub-fuzziness" $MPLAYER_CONFIG 2>/dev/null`
SUB_FUZZINESS_VALUE=`grep  "sub-fuzziness" $MPLAYER_CONFIG 2>/dev/null | sed -n '/1/p'`

#初始化Mplayer vo_driver的设置
init_vo_driver(){
	if [ ! -f $MPLAYER_GUI_CONF ]; then
		echo "vo_driver = \"xv\"" > $MPLAYER_GUI_CONF
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver false
		echo -e "配置文件不存在！建立$MPLAYER_GUI_CONF...\n设定VO_DRIVER为FALSE..."
	else
		if [ ! -z "$VO_DRIVER" ]; then
			if [ "$VO_DRIVER_VALUE" = "x11" ]; then
				gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver true
				echo "Setting VO_DRIVER->TRUE..."
			else
				gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver false
				echo "Setting VO_DRIVER->FALSE..."
			fi
		else
			echo "vo_driver = \"xv\"" >> $MPLAYER_GUI_CONF
			gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver false
			echo "相关字段不存在！初始化...设定VO_DRIVER为FALSE"
		fi
	fi
}
#初始化Mplayer zoom的设置
init_zoom(){
	if [ ! -f $MPLAYER_CONFIG ]; then
		echo "zoom = \"no\"" > $MPLAYER_CONFIG
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/zoom false
		echo -e "配置文件不存在！建立$MPLAYER_CONFIG...\n设定ZOOM为FALSE..."
	else
		if [ ! -z "$ZOOM" ]; then
			if [ ! -z "$ZOOM_VALUE"  ]; then
				gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/zoom true
				echo "Setting ZOOM->TRUE..."
			else
				gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/zoom false
				echo "Setting ZOOM->FALSE..."
			fi
		else
			echo "zoom = \"no\"" >> $MPLAYER_CONFIG
			gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/zoom false
			echo "相关字段不存在！初始化...设定ZOOM为FALSE"
		fi
	fi
}

#初始化Mplayer sub-fuzziness的设置
init_sub_fuzziness(){
	if [ ! -f $MPLAYER_CONFIG ]; then
		echo "sub-fuzziness = 0" > $MPLAYER_CONFIG
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness false
		echo -e "配置文件不存在！建立$MPLAYER_CONFIG...\n设定SUB_FUZZINESS为FALSE..."
	else
		if [ ! -z "$SUB_FUZZINESS" ]; then
			if [ ! -z "$SUB_FUZZINESS_VALUE"  ]; then
				gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness true
				echo "Setting SUB_FUZZINESS->TRUE..."
			else
				gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness false
				echo "Setting SUB_FUZZINESS->FALSE..."
			fi
		else
			echo "sub-fuzziness = 0" >> $MPLAYER_CONFIG
			gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness false
			echo "相关字段不存在！初始化...设定SUB_FUZZINESS为FALSE"
		fi
	fi
}

echo "=====================Initializing================"

if [ -f /usr/bin/mplayer ]; then
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/installed true
		init_vo_driver
		init_zoom
		init_sub_fuzziness
	else
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/installed false
		echo "Notice：Mplayer isn't installed"
fi

if [ -f /usr/bin/avant-window-navigator ]; then
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/awn/installed true
	else
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/awn/installed false
		echo "Notice：Avant Window Navigator isn't installed"
fi

echo "=====================Finished================"
