#!/bin/bash

#首先取出gui.conf文件中有vo-driver字段的行，然后交给awk处理，取出由"分隔的第二个字段
MPLAYER_GUI_CONF=`echo ~/.mplayer/gui.conf`
MPLAYER_CONFIG=`echo ~/.mplayer/config`

VO_DRIVER=`grep "vo_driver" $MPLAYER_GUI_CONF |awk -F"\"" '{print $2}'`
ZOOM=`grep "zoom" $MPLAYER_CONFIG | awk -F"=" '{print $2}'`


if [ $1 = "vo_driver" ]; then
	MPLAYER_BOOL=`gconftool-2 -g /apps/ubuntu-tweak/apps/mplayer/vo_driver`
	if [ "$2" = "off" ]; then
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver flase
		sed -e "s/$VO_DRIVER/xv/" $MPLAYER_GUI_CONF > $MPLAYER_GUI_CONF.tmp
		mv $MPLAYER_GUI_CONF.tmp $MPLAYER_GUI_CONF
		echo "选择其他"
	else
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver true
		sed -e "s/$VO_DRIVER/x11/" $MPLAYER_GUI_CONF > $MPLAYER_GUI_CONF.tmp
		mv $MPLAYER_GUI_CONF.tmp $MPLAYER_GUI_CONF
		echo "选择x11"
	fi
fi

if [ $1 = "zoom" ]; then
	MPLAYER_BOOL=`gconftool-2 -g /apps/ubuntu-tweak/apps/mplayer/zoom`
	if [ "$2" = "off" ]; then
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/zoom flase
		sed -e 's/zoom.*/zoom=no/' $MPLAYER_CONFIG> $MPLAYER_CONFIG.tmp
		mv $MPLAYER_CONFIG.tmp $MPLAYER_CONFIG
		echo "关闭ZOOM"
	else
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/zoom true
		sed -e 's/zoom.*/zoom=yes/' $MPLAYER_CONFIG> $MPLAYER_CONFIG.tmp
		mv $MPLAYER_CONFIG.tmp $MPLAYER_CONFIG
		echo "打开ZOOM"
	fi
fi

if [ $1 = "sub-fuzziness" ]; then
	MPLAYER_BOOL=`gconftool-2 -g /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness`
	if [ "$2" = "off" ]; then
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness flase
		sed -e 's/sub-fuzziness.*/sub-fuzziness=0/' $MPLAYER_CONFIG> $MPLAYER_CONFIG.tmp
		mv $MPLAYER_CONFIG.tmp $MPLAYER_CONFIG
		echo "关闭sub-fuzziness"
	else
		gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/sub-fuzziness true
		sed -e 's/sub-fuzziness.*/sub-fuzziness=1/' $MPLAYER_CONFIG> $MPLAYER_CONFIG.tmp
		mv $MPLAYER_CONFIG.tmp $MPLAYER_CONFIG
		echo "打开sub-fuzziness"
	fi
fi	
