#!/bin/bash

#首先取出gui.conf文件中有vo-driver字段的行，然后交给awk处理，取出由"分隔的第二个字段
MPLAYER_GUI_CONF=`echo ~/.mplayer/gui.conf`
MPLAYER_CONFIG=`echo ~/.mplayer/config`

VO_DRIVER=`grep "vo_driver" $MPLAYER_GUI_CONF |awk -F"\"" '{print $2}'`
ZOOM=`grep "zoom" $MPLAYER_CONFIG | awk -F"=" '{print $2}'`

#初始化Mplayer的设置
if [ -z $VO_DRIVER ]; then
	gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver false
	echo "初始化完成"
elif [ $VO_DRIVER = "x11" ]; then
	gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver true
	echo "初始化完成"
else
	gconftool-2 --set --type boolean /apps/ubuntu-tweak/apps/mplayer/vo_driver false
	echo "初始化完成"
fi


