C=gcc
all:
	$(CC) `pkg-config --cflags --libs gtk+-2.0 gconf-2.0` main.c ubuntu-tweak.c about.c interface.c startup.c session_page.c personality.c desktop_page.c system_page.c security.c applications.c mplayer_page.c -o ubuntu-tweak
